version: "3"

services:
  ####################################
  # Setup node container
  # fichier : /srv/app/docker-bookstore-backend
  ###################################
  backend:
    build: ./backend
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./backend/src:/srv/app/docker-bookstore-backend/src
    links:
      - mongo
    command: npm run start

    ################################
    # mongo db setup
    ################################

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  ####################################
  # Setup client container
  # fichier : /srv/app/docker-bookstore-frontend
  ###################################
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./frontend/src:/srv/app/docker-bookstore-frontend/src
      - ./frontend/public:/srv/app/docker-bookstore-frontend/public
    links:
      - backend
    command: npm run start
